### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by Frotty** [fpirola/java-formatter-eclipse-mars#1]
When trying to import the .xml eclipse throws following error on 4.4 and 4.5:

```
Problems reading profiles from XML
The processing instruction target matching "[xX][mM][lL]" is not allowed.
```

The license in the top breaks it. You have to remove it, or move it somewhere else. 
Eclipse expects the first line to be the xml header

**Comment by fpirola** [comment]
Hi Frotty,
thanks for the tip. Fixed :)
